name: Deploy Locally
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Copy files to web directory
        run: |
          # Remove 'sudo' - it is no longer needed because you own the folder!
          rsync -av --delete --exclude='.git' . /var/lib/vz/my-website/